name: Test NIFTY Data

on:
  workflow_dispatch:

jobs:
  get-nifty-data:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install libraries
        run: |
          pip install openchart google-cloud-bigquery pandas pyarrow

      - name: Get NIFTY data and upload to BigQuery
        run: |
          python get_nifty_data.py
