name: NIFTY Data Collection

on:
  workflow_dispatch:

jobs:
  get-nifty-data:

    runs-on: ubuntu-latest

    steps:

      - name: Get repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install libraries
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/marketcalls/openchart.git
          pip install google-cloud-bigquery pandas pyarrow

      - name: Check OpenChart installation
        run: |
          python -c "import openchart; print('OpenChart imported successfully')"
          pip show openchart

      - name: Get NIFTY data
        run: |
          python get_nifty_data.py
