name: Test NIFTY Data

on:
  workflow_dispatch:

jobs:
  get-nifty-data:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install libraries
        run: |
          pip install requests pandas

      - name: Get NIFTY data
        run: |
          python get_nifty_data.py
